### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#101]
@pruemmer @rodykersten what does [this code](https://github.com/jayhorn/jayhorn/blob/cf1f783433e9ab2f13429a8da66c367e142ff7c4/jayhorn/src/main/java/jayhorn/hornify/encoder/MethodEncoder.java#L234) do? Did we agree on where we implement the 'lastPushID' stuff?

**Comment by rodykersten** [comment]
Closed. We put this in the StatementEncoder.
