### ISSUE TITLE
More precise array model

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#107]
Arrays are currently only precise up to 5 elements. Implement support for array invariants that can be disjunctive on the index.

**Comment by rodykersten** [comment]
Looks like the current array model is broken (see tests in jayhorn/src/test/resources/horn-encoding/arrays/, Sat02-04 used to work). Probably due to #86. We'll have to fix that first.

**Comment by rodykersten** [comment]
I've got to run now, but: the ArrayTransformer build a correct constructor body for JayHornArray_char, however, somewhere along the way it gets lost. The CfgStubber therefore builds a stub and we havoc the length and other fields.

**Comment by martinschaef** [comment]
Looking into it.

**Comment by rodykersten** [comment]
Actually I think I just fixed it.

**Comment by martinschaef** [comment]
Damit ... just did the same

**Comment by martinschaef** [comment]
Phone?

**Comment by rodykersten** [comment]
Reopened, because the bug was fixed but there's no new model yet ;)

**Comment by rodykersten** [comment]
The new array model works and is sound on the limited test cases we currently have. It needs more testing (please add cases to the test/resource/horn-encoding/arrays directory!) and there are a few bugs that I'm aware of. One is related to library methods that return an array. Another one (?) causes the solver to throw an Exception on more tests than before. Also, multi-dimensional arrays are not yet supported. They also don't work with the old model (anymore?). I'll open a separate issue for that, since I probably won't get to it before my vacation.

The model works as follows. I've added a single data field to the array class, of the element type. The get/set/constructor methods access this data field only; e.g., when you call set, you write to this field no matter what the index. Then, in the StatementEncoder, I add an extra parameter to the invariant for any of these methods: the index. For get and set this is the method parameter; for the constructor it is unbound (thus: all indices are set to the default value for the type).

To test run SimpleHornTest, which is currently set-up to run the tests in the directory mentioned above.

**Comment by rodykersten** [comment]
One test case is failing with an exception in the prover: backlog/SatArrayInit. Gotta look into that one. Other than that, the new array model is done.

**Comment by rodykersten** [comment]
Seems to be an Eldarica issue. Closing.
