### ISSUE TITLE
Pull still moves in the wrong place

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#112]
I create a test case `backlog/UnsatIssue112.java` that shows how pull still moves in the wrong place for some cases:
```java
public class UnsatIssue112 {
	public int i;
	public static void main(String[] args) {	
		UnsatIssue112[] as = new UnsatIssue112[2];
		UnsatIssue112 tmp = as[0];
		int x = tmp.i;
		assert false;
	}
}
```
If you look at the cfg code that implements `int x = tmp.i;` you'll find the following:
```
(ln 6)	$ex_, r2 := call <JayArray_UnsatIssue112: UnsatIssue112 get(int)>(r1, 0)
(ln 7)	r2_i_03 := pull(UnsatIssue112, r2)
(ln 7)	$assert_10 := (r2 != $null$)
```
As you can see, it first gets the element from the array at position `0` which has the value `null`. Then it pulls `r2` (which is `null`) before checking nullness. Pulling on `null` introduces the assume false.

**Comment by rodykersten** [comment]
I'm looking in to this. Obviously should not happen. I check whether all the variables are distinct from the object pulled and it seems getUseIdentifierExpressions() is not returning all of them for that assert.

**Comment by rodykersten** [comment]
This was caused by the fact that null checks are spread over two statements:
```
(ln 7)	$assert_7 := (r2 != $null$)
(ln 7)	assert $assert_7
```
The PushPullSimplifier would move the pull past both. I added a check to identify these null checks and, in case it is a null check for the object that is being pulled, not move past it.
