### ISSUE TITLE
Support for multi-dimensional arrays

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#115]
There is some code for multi-dimensional arrays with the old array model, but it does not work / was not maintained.

**Comment by martinschaef** [comment]
Where is that? Multi-dimensional arrays are a bit nasty in Java ... so we have to test that carefully.

**Comment by rodykersten** [comment]
The existing code is in the ArrayTranformer, starting from line 459

**Comment by martinschaef** [comment]
It was somewhat maintained, but it still is unsound. Added two test at `jayhorn/src/test/resources/horn-encoding/multi_array/` and will work on it.

**Comment by martinschaef** [comment]
Should be sound now ... let me downgrade to enhancement.

**Comment by martinschaef** [comment]
It still is a bug because multi arrays get initialized in the wrong way:
```int[][] a = new int[1][2]```
Gets initialized as an array of arrays, but the inner arrays get initialized to `null` but should be initialized to arrays of size `2`.
Working on that now.
