### ISSUE TITLE
PushStatement fascist HashCode

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#119]
@rodykersten what is that thing with the hashCode and equals method in `PushStatement`? I just spent a couple of hours debugging my data-flow analysis until I figured out that push statements have a very liberal idea of what "equal" means ... can we change that? What will it break if I remove your overloading?

**Comment by rodykersten** [comment]
This was only to make sure there were no affecting push id's doubled in the Horn encoding of PullStatement. As PushStatements are sometimes copied (when they are moved into multiple succeeding basic blocks in the CFG), it could happen that the same invariant was assumed several times at a pull. I'm ruling that out in the StatementEncoder now.
