### ISSUE TITLE
Syntax error in .smt2 output file

### ISSUE THREAD

**Issue by jpgallagher** [jayhorn/jayhorn#131]
I'm getting a syntax error in the .smt2 output, from running jayhorn on the following
 small Java program.  The smt2 output is also attached 
[NLogN2_0.smt2.txt](https://github.com/jayhorn/jayhorn/files/719836/NLogN2_0.smt2.txt), for which z3 generates the following syntax errors.

(error "line 127 column 442: invalid qualified/indexed identifier, '_' or 'as' expected")
(error "line 137 column 273: invalid qualified/indexed identifier, '_' or 'as' expected")

It seems to be the symbol "_eps" occurring on these lines, and I see that the .horn output from jayhorn also contains "\eps".

public class NLogN2 {
	public int funNLogN2 (int entry) {
		if (entry < 2) 
			return 1;
		else 
			return 
			aux(entry) + funNLogN2 (entry/2) + funNLogN2 (entry/2);
	}

	public static int aux (int entry) {
		if (entry <= 0) 
			return 1;
		else
			return entry * aux (entry - 1);
	}
	
	 public static void main (String[] a) {

		NLogN2 c = new NLogN2();
		c.funNLogN2(41);
	}
}

**Comment by pruemmer** [comment]
Closed in b5b1601f104530d23b9e8872c214cb12939b90f0
Note that the program also contains non-linear arithmetic, which we currently don't handle in a meaningful way. Surprisingly JayHorn does not crash ...
