### ISSUE TITLE
Simplification appears broken

### ISSUE THREAD

**Issue by jtoman** [jayhorn/jayhorn#155]
Experimenting with Jayhorn as a part of my research, I discovered Jayhorn fails to verify the following trivial program:

```java
class Trivial {
	public static class Ptr {
		public int a;
	}
	
	public static void main(String[] args) {
		Ptr p = new Ptr();
		p.a = Havoc_Class.havoc_int();
		int d = p.a;
		p.a += 1;
		assert d < p.a;
	}
}
```

Looking at the CFG output with the `-cfg` option, immediately after the update the IR contains a check that `i2 < i2`, which naturally fails.

**Comment by pruemmer** [comment]
This should be fixed by the latest commit, 4f998aa
