### ISSUE TITLE
Project Description?

### ISSUE THREAD

**Issue by hrj** [jayhorn/jayhorn#2]
Hi,

I found your other projects (Bixie, etc) interesting and am keeping a watch on this one too. Can you please put a few lines of what this is about. I am compiling a list of static-analyser tools for Java [here](https://github.com/hrj/awesome-eclipse/wiki), and want to describe jayhorn (either now, or when it is ready).

thanks!

**Comment by martinschaef** [comment]
It will be a static verifier that uses a Horn clause solver under the hood... but the will take some time. In terms of description: its http://seahorn.github.io/ for Java.
