### ISSUE TITLE
ArrayTransformer breaks for array type fields

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#36]
The ArrayTransformer gives a NullPointerException when an array type field of another class is used. I added test cases Sat03 and Unsat03 for this under horn-encoding/arrays.

**Comment by martinschaef** [comment]
Will look into it, thx.

**Comment by martinschaef** [comment]
Fixed with commit above.

**Comment by rodykersten** [comment]
Thanks @martinschaef !
