### ISSUE TITLE
Missing handling of runtime exceptions after call

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#57]
The test case SatInterproc in mem-precision fails. The reason seems related to precision in the InterproceduralPushPullOrdering. JayHorn does not properly detect that only the push in the called method setField can affect the assertion. I implemented the mustShadow method, but reading the javadoc now it looks like I did not do it as intended.

**Comment by martinschaef** [comment]
I looked into it and I think there is actually a different problem. If you look at the output:

In method `setField`:

```
(ln 7)	r0 := $in_0
	goto:
	  if (r0 == $null): Block2
	  if (!(r0 == $null)): Block3
Block2:
(ln 8)	assume ($new2 != $null)
(ln 8)	$helper2 := $new2
(ln 8)	java.lang.NullPointerException_serialVersionUID3, $helper2_$dynamicType_4704 := call 
...
Block3:
(ln 8)	r0_i_00, r0_$dynamicType_5771 := pull(A, r0)
(ln 8)	r0_i_00 := 42
```

and then in  `main`:

```
(ln 13)	call <SatInterproc: void setField(A)>(r1)
(ln 15)	r1_i_02, $r2_$dynamicType_5771 := pull(A, r1)
(ln 15)	$i0 := r1_i_02
(ln 15)	push(A, r1, [r1_i_02, $r2_$dynamicType_5771])
	goto:
	  if ($i0 == 42): Block2
	  if (!($i0 == 42)): Block3
``` 

You can see that there is a path in `setField` where a `NullPointerException` is generated and thus `i` is not updated. However, `main` does not pick up this exception. In this case there is actually a path that goes from the constructor of `A` that initializes `i` to zero to the `assert i==42`.

However, apart from that, if you run the example with `-rta`, it still fails and that should be your ball, I guess.

**Comment by rodykersten** [comment]
@martinschaef that is actually exactly why I opened this issue (open your own issue about exceptions, you bully :P ) ->
"JayHorn does not properly detect that only the push in the called method setField can affect the assertion. I implemented the mustShadow method, but reading the javadoc now it looks like I did not do it as intended."
I'm not sure how to implement mustShadow, we should have a call about it soon.

**Comment by martinschaef** [comment]
All your issue are belong to us!
But it's a real bug on my side: if you don't run `-rta`, the `i=0` in the constructor of `A` actually can reach the assertion in `main` ... so this is my bug now.
Let's talk about mustShadow tomorrow - but I have meetings after 2pm, so it has to be early.
