### ISSUE TITLE
Add call site to push

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#58]
Test case SatInstances fails, because the field of an object is set by the method setI twice. This method is called at two different locations, yet the solver cannot distinguish between these since both have the same push ID. We could make the memory model more precise by adding call site, similar to pushID.

**Comment by martinschaef** [comment]
Let's post the test case for reference first:

```java
  public static void main(String[] args) {
     A a = new A();
     A b = new A();
     a.setI(41);
     b.setI(42);
     assert a.i==41;
  }
```

Shouldn't it be sufficient that `a` and `b` are guaranteed to be different? I added a flag `-callid` to add the line number but that doesn't seem to make difference.

**Comment by rodykersten** [comment]
findBugs notes that the call id is not actually used (you just added it to the havoc, not the pull/push and I just remove the havoc to address issue #65). That's probably why SatInstances still fails. Will work on this tonight. Now that I'm thinking about it, the current alias analysis is not precise enough to detect that a and b are different. I will add an issue for that.

**Comment by rodykersten** [comment]
What you were getting @martinschaef is the line number for the push, but that cannot make a difference as the push already has a unique ID. I meant adding the location where the method is called from, but I think that's not a good idea. The way to go is probably to use a more precise alias analysis. I'm merging this with #71.

**Comment by martinschaef** [comment]
@rodykersten I actually implemented passing the line number into the method if you use the `-callid` option. For example, when running `SatInterproc` with that, you get intermediate code like this:

```
(ln 12)	$r2_$dynamicType_5771 := call <A: void <init>()>($r2, 1787079037)
(ln 12)	r1 := $r2
(ln 13)	call <SatInterproc: void setField(A)>(574268151, r1)
```

You can see the large int that gets passed into the method? That's hashcode of the call statement. We could also just enumerate them.

**Comment by pruemmer** [comment]
I actually have a simpler idea how we can handle the `a.i==41` example: we should start to systematically inline sufficiently simple methods. For a function like `setI` it does not make sense to derive a full contract, much more reasonable to inline such calls (on the CFG level). We then get two separate push locations and can distinguish 41 and 42.

I would expect inlining to lead to significant speed-up in general, and it will also make our memory model much more effective, since all setters and getters are gone. After expanding virtual dispatch, we could say that a method `m` is inlined if
* `m` does does call itself (indirect calls are ok)
* `m` is shorter than N instructions, or `m` is called at most K times in the program. (say, N=10 and K=2)

**Comment by rodykersten** [comment]
Since inlining does not seem to help and the old implementation of this was not correct, I want to try again. Re-opening.

**Comment by martinschaef** [comment]
I started working on this in the `caller_id` branch but it's currently unsound and I'd need some help with #99 before I can make real progress.

**Comment by rodykersten** [comment]
@martinschaef what's the status of this one? I didn't fully remove the ghost variables from push and pull yet, as it's used by this callerID stuff. It's probably better to - similar to last push - have a dedicated field for this in the PushStatement/PullStatement classes and handle this in the StatementEncoder.

**Comment by martinschaef** [comment]
I'm not sure. My first attempt sucked, but the idea was pretty naive - I'm still convinced that having the calling context may be useful. However, just passing in the id of the immediate caller will not be a solution. I'll think more about it.
Leave these ghost fields around. We do not use them right now, but I'm pretty sure we'll find an application for them. In the end, we might want to be able to pass stuff to push and pull that's not part of the object at some point.

**Comment by martinschaef** [comment]
Since we have no idea if this adds any value, I close the issue.
