### ISSUE TITLE
With -mem-prec 0, JayHorn is less precise than expected

### ISSUE THREAD

**Issue by pruemmer** [jayhorn/jayhorn#66]
Even with  -mem-prec 0, I would expect JayHorn to be able to verify the following program:

```
public class Test {
    public int x;
    public Test (int x) {
        this.x = x;
    }

    public static Test a = null;

    public static void main(String[] args) {
        for (int i = 0; i < 3; ++i)
            a = new Test(i+1);
        assert(a.x > 0);
    }
}
```

since it is enough to figure out the object invariant "x > 0". JayHorn thinks this program is unsafe however.

The example works fine without the -mem-prec 0

**Comment by martinschaef** [comment]
Added [unit test](https://github.com/jayhorn/jayhorn/blob/b8d6da440640ab0e31eb8a68216fecfdd9ee8f2d/jayhorn/src/test/resources/horn-encoding/backlog/SatIssue66.java) with this snippet.  Fails with -mem-perc 0, and 1 but should pass. Throws an exception for -mem-prec >= 2

**Comment by rodykersten** [comment]
Programs with constructors actually never worked at mem-prec 0 AFAIK. If you remove that, i.e. check the variation below, then it works at mem-prec 0.
`public class SatIssue66 {
    public int x;
    public static SatIssue66 a = null;

    public static void main(String[] args) {
        SatIssue66 a = null;
        for (int i = 0; i < 3; ++i) {
            a = new SatIssue66();
            a.x = i+1;
        }
        assert(a.x >= 0);
    }
}
`

**Comment by rodykersten** [comment]
The exception thrown at mem-prec>=2 however, that one pointed me to a tricky off-by-one that made the pushIDAdder skip a push... Fixed with my next commit.
