### ISSUE TITLE
Unsoundness in improved memory model

### ISSUE THREAD

**Issue by pruemmer** [jayhorn/jayhorn#67]
With options `-rta -mem-prec 0`, the attached program is correctly identified as unsafe. When I remove the `-mem-prec 0`, the program suddenly becomes safe.
[BinaryTreeSearch.java.zip](https://github.com/jayhorn/jayhorn/files/474677/BinaryTreeSearch.java.zip)

**Comment by pruemmer** [comment]
Might be related to #57

**Comment by martinschaef** [comment]
Merged with #68
