### ISSUE TITLE
Move all stubbing to CFG side

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#70]
We now have a MethodStubber that works on Jimple and a CfgStubber that works on CFG level. Fooling around with library methods is messy. Better to move all functionality of the MethodStubber into CfgStubber if possible.

**Comment by martinschaef** [comment]
This is indeed annoying. The reason why I did not merge them back then was as follows:
The `CfgStubber` should only replace a method by something that havocs the return value and do nothing if there is no return value.
The `MethodStubber` should deal with the problem that there are many constructors that do not have a body. If we don't add a body that sets the dynamicType, we get `assume false` all over the place. I.e., constructors have to be stubbed differently from other methods. 

But, indeed, they could be merged. And I think once #47 is done, this will become trivial.
