### ISSUE TITLE
SpecTests fail on translation to Horn with or without using specs

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#72]
7 of the SpecTests fail on this assertion on line 185 of StatementEncoder:
Verify.verify(!cs.getReceiver().isEmpty() || calledMethod.getReturnType().isEmpty());

**Comment by pruemmer** [comment]
I thought I commented this line ... I don't think the assertion actually makes sense, at least not anymore?

**Comment by martinschaef** [comment]
True ... that came back in when I reverted my changes in the StatementEncoder.
