### ISSUE TITLE
Method inlining

### ISSUE THREAD

**Issue by pruemmer** [jayhorn/jayhorn#73]
Copied from #58 

I actually have a simpler idea how we can handle the `a.i==41` example: we should start to systematically inline sufficiently simple methods. For a function like `setI` it does not make sense to derive a full contract, much more reasonable to inline such calls (on the CFG level). We then get two separate push locations and can distinguish 41 and 42.

I would expect inlining to lead to significant speed-up in general, and it will also make our memory model much more effective, since all setters and getters are gone. After expanding virtual dispatch, we could say that a method `m` is inlined if
* `m` does does call itself (indirect calls are ok)
* `m` is shorter than N instructions, or `m` is called at most K times in the program. (say, N=10 and K=2)

**Comment by martinschaef** [comment]
I'll look into this when I start working on #57

**Comment by martinschaef** [comment]
@pruemmer in branch `issue_73` I added two new flags `-inline_count` and `-inline_size`. JayHorn tries to inline any procedure whose size (in number of instructions before inlining) is less than `-inline_size` or who are called less than `-inline_count` number of time.
Self-calls are not inlined. 

The results don't indicate any improvement. Can you test it and look into the inlined code if this is what you had in mind? It would be good if we could add test cases that fail without inlining and succeed with inlining.

**Comment by pruemmer** [comment]
I'm looking at this right now. For some examples, inlining does indeed give a significant speed-up; but currently it does not help for the `a.i==41` example. This is puzzling, since the example works if I do the inlining by hand (on the source level).

To verify, inlining is done _before_ pushs/pulls are optimised?

**Comment by pruemmer** [comment]
It seems to me that this might be the problem, the inlining is happening too late?

**Comment by martinschaef** [comment]
@rodykersten is there any steps you do that should happen *after* the inlining? Right now, the inlining happens at the very end. It also deletes all methods in the program that are not reachable from the entry point. 
I'm also thinking of implementing sth that propagates constants (and removes assignments in basic blocks. After the inlining, there are a lot of statements that can be dropped... I'll start a separate issue for that.

**Comment by rodykersten** [comment]
Yes, simplification could be more effective and alias analysis and adding of push id's could be more precise if you do inlining before.

**Comment by martinschaef** [comment]
Would you mind taking a look at this? The inlining is just [these two lines](https://github.com/jayhorn/jayhorn/blob/devel/jayhorn/src/main/java/jayhorn/checker/Checker.java#L50), so it should be easy to move around. Note that it throws away methods and deep-copies blocks, so any reference to statements that you build up may break during inlining.

This should solve several issues at once, if it works.

**Comment by rodykersten** [comment]
Sure, though it'll probably be Tuesday or later.

**Comment by martinschaef** [comment]
@rodykersten on MinePump, inlining makes everything timeout (even for large timeouts). We should look into this. But more importantly, we should do the inlining before your alias analysis etc.

**Comment by rodykersten** [comment]
Managed to move inlining before the optimizations. The problem was unsoundness in the moving of pushes and pulls. It did not actually use the points to analysis yet. But it does now. Big soundness test looks good. Will test on benchmarks tomorrow.

**Comment by rodykersten** [comment]
Merged with the recent version. Inlining breaks (only) some of the examples in mem-precision. Not sure why yet.

**Comment by rodykersten** [comment]
I figured out two things: 
- Inlining of constructors breaks the points to analysis. The PTA determines alias classes based on constructor calls. I disabled inlining of constructors to fix this.
- Inlining creates copies of variables, of which JayHorn does not know they are related to others. This breaks e.g. SatAliasing01 in mem_precision. I realized that the points-to analysis does not merge alias classes at pulls, which could be the problem here.

Also fixed a bug; now this branch is slightly more precise than devel, as long as inlining is disabled:
**************************************
unsound: 0     exception: 5     imprecise: 26    correct: 106  
**************************************

**Comment by rodykersten** [comment]
Turns out the two failing tests SatAliasing01 and 02 are due to very limited dead code elimination. So, they will be fixed in #82. I'm closing this one and merging my code back into devel.
