### ISSUE TITLE
Strange soundness error for Switch over Enum in Subpackage

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#85]
The following two-file program gives unsound results:

```java
import MinePumpSystem.Environment; 
public  class  Main {
	Environment env;
	public static void main(String[] args) {
		assert false;  //<=== should fail
    }
}
```

```java
package MinePumpSystem; 
public class  Environment {
	public enum  WaterLevelEnum { low }
	private WaterLevelEnum waterLevel = WaterLevelEnum.low;
	void lowerWaterLevel() {				
		switch (waterLevel) {
		}
	}
}
```

Test case for this is in `jayhorn/src/test/java/jayhorn/test/assorted_tests/MutliFileTest.java`.

Random observations so far:

  - bug occurs because of the Switch and the Enum. If we change the switch into an if, or the enum into an int, it goes away.
  - bug only occurs if the two files are not in the same package. If Environment is a nested class of Main or in the same package, everything is fine.

**Comment by rodykersten** [comment]
Great job @martinschaef

**Comment by martinschaef** [comment]
That was too fast. It's still broken for some examples. Pushing new tests in a second.

**Comment by martinschaef** [comment]
Just downgraded it from bug to enhancement since the current version at least does not do anything unsound on our benchmarks.

**Comment by martinschaef** [comment]
I close this because it is a duplicate of #89.
