### ISSUE TITLE
Array bounds check bug

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#86]
It seems to me that (definitely without the -rta option), SatIssue86 should pass. This is why we get UNSAFE for InsertionSort, even without an assertion.

``` java
public class SatIssue86 {
  public static void main(String[] args) {
        int N = 5;
        try {
                N = Integer.parseInt(args[0]);
        } catch (Exception e) { }
      if (N<0 || N>5) return;

        int a[] = new int[N];
        for (int i = 0; i < N; i++) {
            a[i] = 2;
        }
  }
}
```

**Comment by martinschaef** [comment]
Note that rta only treats all runtime exceptions as assertions. Even without the rta, there will be a bounds check. And since you're in main, this will become an assertion one way or the other. 
You should add an `if (args.length < ?) return` in the beginning.

---
Martin Schäf

**Comment by martinschaef** [comment]
Ok - email comments don't work well, so here a markdown comment:

The `-rta` option only turns all runtime exceptions as assertions. Even without the `-rta`, there will be a bounds check. And in `main`, this will become an assertion one way or the other since we enforce that `main` does not throw anything.
You should add an `if (args.length < 1) return;` in the beginning.

**Comment by martinschaef** [comment]
This is a simpler version that also fails:

```java
public class SatIssue86 {
  public static void main(String[] args) {
        for (int i = 0; i < args.length; i++) { 
            args[i].toCharArray();
        }
  }
}
```

Probably we should look into the Array stubs. Maybe they are buggy. I'll put it on my list. But I'll do the soundness stuff first.

**Comment by martinschaef** [comment]
Another variation:

```java
public class SatIssue86Minimal {
	public static void main(String[] args) {
		int N = args.length;
		//passes if we propagate N.
		for (int i = 0; i < N; i++) {
			args[i] = null;
		}
	}
}
```
It passes if we replace `N` in the `for` loop by `args.length` and fails otherwise ...

**Comment by martinschaef** [comment]
`SatIssue86Minimal` works with the tuple encoding (but still throw an exception for mem-encoding 3)

**Comment by rodykersten** [comment]
fixed
