### ISSUE TITLE
Enumerations don't work

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#89]
The reason all those MinePump examples don't work is that they contain an enum. I've added this minimal example that we can't prove:

```
public class SatEnum {

        public enum WaterLevelEnum {low, normal, high}

        public static void main (String args[]) {
                assert WaterLevelEnum.low != null;
        }
}
```

I have to read up on how enum are implemented in Java, but it seems that they are handled as objects but there are no constructors.

**Comment by martinschaef** [comment]
I'm pretty sure that this is because we don't have a good way of handling arrays (there is a bunch of arrays in the bytecode) ... we talked about modifying Push for that. But that's out of scope.

**Comment by rodykersten** [comment]
This works now, closing.
