### ISSUE TITLE
Bug in VirtualCallResolver

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#93]
The example RedBlackTreeSearch in the 'algorithm' dir breaks this assertion in the VirtualCallResolver: Verify.verify(t instanceof ArrayType);

**Comment by martinschaef** [comment]
@rodykersten I'm a bit short on time today. Could you add a unit test to backlog for me then I'll try to fix it tonight.

**Comment by rodykersten** [comment]
We were not planning to add this one to the paper, so better focus on writing maybe?
