### ISSUE TITLE
BinaryTreeSearch: too many pulls, too many pushes?

### ISSUE THREAD

**Issue by pruemmer** [jayhorn/jayhorn#94]
I'm checking right now why BinaryTreeSearch_true does not work, and somewhere in between source code and cfg strange things seem to happen. The code is:

```
                    if (curr.right != null) {       // line 81
                        curr = curr.right;          // line 82
                    } else {
                        curr.right = new Node(v, null, null);
                        break;
                    }
```

and the resulting cfg is:

```
Block6:
(ln 81) r7_value_03, r7_left_3254, r7_right_3265, r7_$dynamicType_5526, lastpush := pull(BinaryTreeSearch_true$BinaryTree$Node, r7)
(ln 81) assume (((((((((lastpush == 19) || (lastpush == 5)) || (lastpush == 23)) || (lastpush == 6)) || (lastpush == 7)) || (lastpush == 8)) || (lastpush == 9)) || (lastpush == 10)) || (lastpush == 11))
(ln 81) $r4 := r7_right_3265
    goto:
      if ($r4 == $null$): Block7
      if (!($r4 == $null$)): Block8
Block8:
(ln 82) r7_value_03, r7_left_3254, r7_right_3265, r7_$dynamicType_5526, lastpush := pull(BinaryTreeSearch_true$BinaryTree$Node, r7)
(ln 82) assume (((((((((lastpush == 19) || (lastpush == 5)) || (lastpush == 23)) || (lastpush == 6)) || (lastpush == 7)) || (lastpush == 8)) || (lastpush == 9)) || (lastpush == 10)) || (lastpush == 11))
(ln 82) r7 := r7_right_3265
(ln 82) lastpush := 7
(ln 82) push(BinaryTreeSearch_true$BinaryTree$Node, r7, [r7_value_03, r7_left_3254, r7_right_3265, r7_$dynamicType_5526, lastpush])
    goto:
      Block4
```

Two questions:
- why are the pulls in Block6 and Block8 not merged? Block8 only has a single incoming edge; the fact that we have two separate pulls implies that we don't know that `curr != null` after line 82, which in the end leads to the spurious NullPointerException
- why is there a push in Block8? `curr` is a local variable, so the assignment `curr = curr.right` should not lead to any pushes. In fact the push looks unsound, since this will copy the values of fields from `curr` to `curr.right`, which is not what the assignment actually does

**Comment by rodykersten** [comment]
Question 1:

They are not merged because of a restriction on moving push/pull across the CFG. Before moving e.g. the pull at the start of Block 8 up in the CFG, into Block 6, it is checked whether there is a path through Block 6 that leads to Block 8. There is, through 6, 4 and 10. It is then not moved, to prevent moving statements around in circles.

If we can identify loop headers, then I think we can relax this restriction to not moving past loop headers, but allowing moves inside the loop. That would allow to remove the extra pull in this example. @martinschaef do we have any code to detect loop headers somewhere? I know there's some graph library that we use, which can probably detect dominators etc?

**Comment by rodykersten** [comment]
Question 2:
What we do is add a pull-push pair around every field access (read or write), then apply the simplification rules to remove unneeded ones. There is currently no rule that says that in:
```
a1, a2 = pull(A, a);
..code..
push(a, [a1,a2]);
```
if ..code.. does not update the value of a1 or a2, the push can be removed. We can add that, but it will need to go over all statements in between all pull's and push's of objects of the same (or sub/super) class and see if they may alias. So it will be fairly inefficient.

As for the unsoundness, I think you're right. We are copying the values from curr into curr.right instead of vice versa. I need to think about this some more. There is a mapping from locals to fields where we keep track of copies etc, we should probably do something smarter there when these are of reference-type.

**Comment by pruemmer** [comment]
Concerning 1:
I see. It is not even necessary to compute loop heads though to prevent cycles. One can simple compute the distance of each block from the entry point (say, using Bellman-Ford), and then only allow pulls to move closer to the entry, and pushes to move further away

**Comment by pruemmer** [comment]
Concerning 2:
We can easily optimise by not adding a push in case of reads in the first place?
But I think the unsoundness problem has a different reason: we have to make sure that the reference `a` is not modified in `code`, regardless of whether we are handling reads or writes. Otherwise you will push back to a different object than you pulled from.

**Comment by martinschaef** [comment]
@rodykersten all graph utils are in soottocfg.cfg.util. In particular there is a class LoopFinder<V>. That should have everything you need.

**Comment by rodykersten** [comment]
Thanks, but I already implemented it as @pruemmer suggested. Pushing shortly..

**Comment by rodykersten** [comment]
First two points are implemented in my last commit.

**Comment by pruemmer** [comment]
Thanks!

For BinaryTreeSearch, I now observe the following problem:

```
Method <BinaryTreeSearch_true: void main(JayArray_java_lang_String)>($in_0)
[...]
Block2:
(ln 123)	lastpush := 13
(ln 123)	push(JayArray_java_lang_String, r0, [undef_r0_0, undef_r0_1, JayArray_java_lang_String, undef_r0_2, undef_r0_3, undef_r0_4, undef_r0_5, undef_r0_6, lastpush])
(ln 123)	r0_$length_5810, r0_$elType_5821, r0_$dynamicType_5832, r0_atIndex_0_5843, r0_atIndex_1_5854, r0_atIndex_2_5865, r0_atIndex_3_5876, r0_atIndex_4_5887, lastpush := pull(JayArray_java_lang_String, r0)
(ln 123)	assume (lastpush == 13)
(ln 123)	$helper8 := r0_$length_5810
(ln 123)	$helper9 := 0
(ln 123)	$assert_13 := ($helper9 < $helper8)
(ln 123)	assert $assert_13
```

I can see two problems here: (1) why are the push and pull not merged? and (2) why do we push undef_ values? they seem to be the reason why we get an ArrayIndexOutOfBound exception one line later

**Comment by rodykersten** [comment]
The push is added by the MissingPushAdder. This class adds pushes for pulls that do not have an associated push yet. This is the case e.g. for objects that are returned by a library method or as in this case, are program input. If we don't add that push, the pull becomes an assume(false). You'll see that if you remove that one, you also get SAFE for the _false versions of BinaryTreeSearch.

Note that adding a push for any object returned by a library call is not sound in general, as it could be null or have fields that are uninitialized. However, if we do not assume that these objects and their fields are initialized, it will be practically impossible to verify programs with library calls. We may want to add an option for this in the future.

**Comment by pruemmer** [comment]
I see; but in this case, the additional push comes _after_ some pull from the same object?

**Comment by rodykersten** [comment]
I don't see where that happens here? What should happen on a write to a field a.f is that first we add a pull before and a push after the field access. Then, if there is no push that can affect that pull, we create one with unbound variables. So then we'll have push(a, undef...); a = pull(), a.f = y; push(a, y, ...);. After that we apply the simplification rules, which may or may not remove some of these.

**Comment by pruemmer** [comment]
For the latest JayHorn, I get the following cfg; the push in Block2 should not be necessary, since there is already a push to the same object in Block1?

```
[...]
Root ->Block1:
(ln -1)	$ex_ := $null$
(ln 119)	r0 := $in_0
(ln 119)	$ex_ := call <JayHornAssertions: void <clinit>()>()
(ln 120)	lastpush := 12
(ln 120)	push(JayArray_java_lang_String, r0, [undef_r0_0, undef_r0_1, JayArray_java_lang_String, undef_r0_2, undef_r0_3, undef_r0_4, undef_r0_5, undef_r0_6, lastpush])
(ln 120)	r0_$length_5810, r0_$elType_5821, r0_$dynamicType_5832, r0_atIndex_0_5843, r0_atIndex_1_5854, r0_atIndex_2_5865, r0_atIndex_3_5876, r0_atIndex_4_5887, lastpush := pull(JayArray_java_lang_String, r0)
(ln 120)	assume (lastpush == 12)
(ln 120)	$i1 := r0_$length_5810
	goto:
	  if ($i1 >= 1): Block2
	  if (!($i1 >= 1)): Block3
Block2:
(ln 123)	lastpush := 13
(ln 123)	push(JayArray_java_lang_String, r0, [undef_r0_0, undef_r0_1, JayArray_java_lang_String, undef_r0_2, undef_r0_3, undef_r0_4, undef_r0_5, undef_r0_6, lastpush])
(ln 123)	r0_$length_5810, r0_$elType_5821, r0_$dynamicType_5832, r0_atIndex_0_5843, r0_atIndex_1_5854, r0_atIndex_2_5865, r0_atIndex_3_5876, r0_atIndex_4_5887, lastpush := pull(JayArray_java_lang_String, r0)
(ln 123)	assume (lastpush == 13)
[...]
```

**Comment by rodykersten** [comment]
The duplicated push is no longer there. This is currently failing because of #126 though.

**Comment by rodykersten** [comment]
This now passes, closing.
