### ISSUE TITLE
Print final heap invariants

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#99]
Is there a way to see the assignment that the solver picked for the heap invariants? I'm working on passing the caller ID around and introduced some unsoundness, but it's nasty to debug without seeing what the solver does.

**Comment by pruemmer** [comment]
Option -solution?

**Comment by martinschaef** [comment]
Ah ... didn't know this was working. It's disabled if we have a timeout set for the solver - see [this line](https://github.com/jayhorn/jayhorn/blob/devel/jayhorn/src/main/java/jayhorn/solver/princess/PrincessProver.java#L332). Could we change that?

**Comment by martinschaef** [comment]
found a way of printing, so lets close this for now.
